### ISSUE TITLE
TypeError: Cannot set property 'Your Heading Text' of undefined

### ISSUE THREAD

**Issue by ilyaigpetrov** [nagaozen/markdown-it-toc-done-right#1]
Input:
```md
${toc}


## Foo

##### Bar

abc

## BOOM
```
Output:
```js
TypeError: Cannot set property 'BOOM' of undefined
    at headings_ast (/home/ilyaigpetrov/Repos/sl-sites/node_modules/markdown-it-toc-done-right/index.js:117:31)
    at Object.md.renderer.rules.toc_body (/home/ilyaigpetrov/Repos/sl-sites/node_modules/markdown-it-toc-done-right/index.js:72:20)
    at Renderer.render (/home/ilyaigpetrov/Repos/sl-sites/node_modules/markdown-it/lib/renderer.js:326:38)
    at MarkdownIt.render (/home/ilyaigpetrov/Repos/sl-sites/node_modules/markdown-it/lib/index.js:543:24)
    at /home/ilyaigpetrov/Repos/sl-sites/node_modules/metalsmith-markdownit/lib/index.js:75:28
    at Array.forEach (<anonymous>)
    at /home/ilyaigpetrov/Repos/sl-sites/node_modules/metalsmith-markdownit/lib/index.js:71:28
    at Array.forEach (<anonymous>)
    at Ware.plugin (/home/ilyaigpetrov/Repos/sl-sites/node_modules/metalsmith-markdownit/lib/index.js:59:72)
    at Ware.<anonymous> (/home/ilyaigpetrov/Repos/sl-sites/node_modules/wrap-fn/index.js:45:19)
```
### Details

```js
markdownit({
    html: true,
    linkify: true,
    typographer: true,
  })
  .use(require('markdown-it-anchor'), {
    slugify,
  })
  .use(require('markdown-it-toc-done-right'), {
    slugify,
  });
```

**Comment by nagaozen** [comment]
Could you please describe what do you think it should be the output here?

**Comment by ilyaigpetrov** [comment]
Currently I use `markdown-it-table-of-contents` and I'm delighted with its output:
```js
'use  strict'
const input = ....
const md = require('markdown-it')();
md.use(require('markdown-it-table-of-contents'), { includeLevel: [1, 2, 3, 4, 5] });
console.log(md.render(input));
```
Output (I've manually added numeric suffix which reflects header level):
```html
<p>
<div class="table-of-contents">
  <ul>
    <li>
      <a href="#foo">Foo2</a>
      <ul>
        <li>
          <a href="#bar">Bar5</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="#boom">BOOM2</a>
    </li>
  </ul>
</div>
</p>
<h2>Foo2</h2>
<h5>Bar5</h5>
<p>abc</p>
```

**Comment by nagaozen** [comment]
It sounds reasonable to me... however [W3C](https://www.w3.org/WAI/tutorials/page-structure/headings/#heading-ranks) states that:

> Skipping heading ranks can be confusing and should be avoided where possible: Skipping heading ranks can be confusing and should be avoided where possible: Make sure that a `<h2>` is not followed directly by an `<h4>`, for example. It is ok to skip ranks when closing subsections, for instance, a `<h2>` beginning a new section, can follow an `<h4>` as it closes the previous section.

So, supposing that we care about SEO, shouldn't we be fixing the md file instead?

```md
${toc}

## Foo

### Bar

abc

## BOOM
```

Anyway, it's very possible that i'll be looking for a fix to this case. What do you think about the way <validator.w3.org/nu/> handles this case? _id est_ injecting [missing] elements to the outline?

```
Heading-level outline

<h1> [missing]
	<h2> Foo2
		<h3> [missing]
			<h4> [missing]
				<h5> Bar5
	<h2> BOOM2
```

**Comment by ilyaigpetrov** [comment]
I've migrated my markdown document from GitHub where I used smaller headings because they look smaller. I think you may output a warning _"Skipping heading ranks can be confusing and should be avoided where possible. See https://www.w3.org/WAI/tutorials/page-structure/headings/#heading-ranks"_ and also support a `{ silent: true }` or `{ logLevel: 'warninigs' }` (`{ logLevel: 'silent' }`) options.

https://validator.w3.org/nu/ shows no warnings for skipping heading ranks on my page. E.g. you may try this:
```html
<!DOCTYPE html>
<html
  lang="en-US"
>
  <head>
    <title>Education</title>
  </head>
  <body>
    <h2 id="education">Education</h2>
    <h5 id="mooc">MOOC</h5>
      List of MOOCs: ...
  </body>
</html>
```

**Comment by nagaozen** [comment]
`1.0.5` supports "skipping heading ranks".
