### ISSUE TITLE
[Feature Requests] Optional Generation of the Nav Container Element

### ISSUE THREAD

**Issue by oleersoy** [nagaozen/markdown-it-toc-done-right#10]
Hi,

Thank you for this amazing TOC generator!  I was wondering if it would be possible to add a flag for optional generation of the `<nav class="table-of-contents">` element.

I'm integrating markdown-it-toc-done-right into [@superflycss/cli](https://www.npmjs.com/package/@superflycss/cli).  Authors of MD documents may want to add additional classes to the `nav` element.  For example:

```
<nav class="TableOfContents  u-ol-list-style-none u-background-color-white">
${toc}
</nav>
``` 

Thus this feature would give them design time / pre compile time control of the element.

Would also be really nice if we could control `ol` or `ul` through the name of the tag.  For example:
```
${toc} // Default to ol
or
${tocul} renders the toc using ul
```

**Comment by nagaozen** [comment]
You might be looking for the `containerClass` and `listType` options:

```js
var md = require("markdown-it")({
	html: false,
	xhtmlOut: true,
	typographer: true
}).use( require("markdown-it-anchor"), { containerClass: "TableOfContents  u-ol-list-style-none u-background-color-white", listType: "ul", permalink: true, permalinkBefore: true, permalinkSymbol: '§', slugify: legacySlugify } )
```

**Comment by oleersoy** [comment]
Oh cool!  That looks promising.  Thanks again for this awesome plugin!!
