### ISSUE TITLE
max depth of toc levels

### ISSUE THREAD

**Issue by tessus** [nagaozen/markdown-it-toc-done-right#13]
We are using your module in [Joplin](https://joplinapp.org/) and it recently came to my attention that there's a request to only show the first X levels of headers in the toc.

I did some research and noticed that other toc implementations provide an option to set the number of levels or max depth.

Is there any chance you could add such an option as well? From a coding standpoint, it should not be too complicated to make this happen.

**Comment by nagaozen** [comment]
It's already possible using the array notation on the level option. See line 50 of `tests.js`.

**Comment by tessus** [comment]
Ah, I see. Thank you.

**Comment by rauschma** [comment]
Nice! Suggestion: mention this in the readme.
