### ISSUE TITLE
[BUG] headings with the same text are not correctly handled

### ISSUE THREAD

**Issue by desk7** [nagaozen/markdown-it-toc-done-right#14]
I know that it is an uncommon event, but I noticed that if you enter two or more headings of the same level with the same title one after another, only the first one will appear in the TOC.
```
# Title
text
## Section
example
### subSection
text
### subSection
text
# else
```
In that case only the first h3 heading will appear.

**Comment by nagaozen** [comment]
Fixed in 4.0.2
