### ISSUE TITLE
Ability to exclude headings from TOC

### ISSUE THREAD

**Issue by mashdot** [nagaozen/markdown-it-toc-done-right#15]
I am migrating from using Kramdown, and wondered if there is functionality to exclude headers from the TOC?

In Kramdown... 

```
# Header 1

## Header 2
{:.no_toc}

## Header 3
```

Would result in just creating the TOC with "Header 1" and "Header 3", excluding "Header 2" from the list.

Reference: https://kramdown.gettalong.org/converter/html.html#toc

**Comment by nagaozen** [comment]
Maybe with an option? Exclude: []?

**Comment by nagaozen** [comment]
Just another question, when using this syntax, you end up with a paragraph with `{:.no_toc}` text, don't you?

`<nav class="table-of-contents"><ol><li><a href="#header-1"> Header 1</a><ol><li><a href="#header-2"> Header 2</a></li><li><a href="#header-3"> Header 3</a></li></ol></li></ol></nav><h1 id="header-1"><a class="header-anchor" href="#header-1" aria-hidden="true">§</a> Header 1</h1>
<h2 id="header-2"><a class="header-anchor" href="#header-2" aria-hidden="true">§</a> Header 2</h2>
<p>{:.no_toc}</p>
<h2 id="header-3"><a class="header-anchor" href="#header-3" aria-hidden="true">§</a> Header 3</h2>
<p>Lorem ipsum dolorem sit amet</p>`

**Comment by nagaozen** [comment]
Oh, I see ... you are probably using `markdown-it-kramdown-attrs`. This should be mentioned when opening the issue.

**Comment by mashdot** [comment]
Middleman just uses Kramdown by default

```
- TOC
{:toc}

# Header 1

## Header 2
{:.no_toc}

## Header 3
```

Results in...

```
<ul id="markdown-toc">
  <li><a href="#header-1" id="markdown-toc-header-1">Header 1</a>    <ul>
      <li><a href="#header-3" id="markdown-toc-header-3">Header 3</a></li>
    </ul>
  </li>
</ul>

<h1 id="header-1">Header 1</h1>

<h2 class="no_toc" id="header-2">Header 2</h2>

<h2 id="header-3">Header 3</h2>
```

**Comment by nagaozen** [comment]
Just noticed that it's already possible to exclude headings from TOC using level array notation. For example: `level: [1,3]` will only make a table of contents for headers H1 and H3

**Comment by mashdot** [comment]
Thanks @nagaozen that excludes all headers of a certain level. I was looking to exclude a specific header instance. This is useful if you want to keep the headings in an article, but perhaps just exclude one such as an aside block.

**Comment by vladfaust** [comment]
The issue is still relevant.

**Comment by joapuiib** [comment]
Looking exactly for this. It would be nice to exclude specific headers from the TOC, as kramdown does.
