### ISSUE TITLE
Markdown-it as Peer Dependency?

### ISSUE THREAD

**Issue by ilyaigpetrov** [nagaozen/markdown-it-toc-done-right#2]
Would you like to move `markdown-it` from devDependencies to [peerDependencies](https://nodejs.org/en/blog/npm/peer-dependencies/)? I guess your case fits the goal of peer dependencies just well.

**Comment by nagaozen** [comment]
You are completely right!

**Comment by nagaozen** [comment]
`1.0.5` moved `markdown-it` from `devDependencies` to `peerDependencies`

**Comment by ilyaigpetrov** [comment]
I've googled and [found out][1] you may use `before_install` travis hook to install `markdown-it` without pushing it in `devDependencies`. I like this solution more, but you are free to have a different preference.

[1]: https://stackoverflow.com/a/37738197/521957
