### ISSUE TITLE
TOC Automatically sorts some Headers in Rendered view

### ISSUE THREAD

**Issue by Perkolator** [nagaozen/markdown-it-toc-done-right#20]
Hello, I was asked in [Joplin repo ](https://github.com/laurent22/joplin/issues/1843) to post this problem here.

Joplin version used: Windows 1.0.165

## Steps To Reproduce

1. Download and import/paste this md test file to Joplin: [test.md.txt](https://github.com/laurent22/joplin/files/3561641/test.md.txt)
2. Change the layout to side-by-side raw & rendered view.

= Rendered view shows these TOC entries/links in incorrect order compared to the raw/md text:
- Headers with numbers 0-4 and 6-9 are put on top of the TOC, although those headers are located after header "z". (Header "5 test" is not affected, it's in correct place in the TOC.)
- Header with number 0 is put as the first TOC entry, although it's actually after header 9.

Here's a screenshot from Joplin that shows the beginning of the TOC in side-by-side raw/md & rendered view:

![joplin](https://user-images.githubusercontent.com/53913724/64134159-17f9df80-cde4-11e9-95be-e0eb4de66976.png)

Expected behavior: All TOC entries/links in rendered view should be in the order that they are in the raw/md text, i.e. no sorting.

**Comment by Perkolator** [comment]
Is this project still alive? Do you need more information?

**Comment by nagaozen** [comment]
Hi! It's alive! PR's are welcome!

**Comment by nagaozen** [comment]
Confirmed as a bug.

**Comment by nagaozen** [comment]
Fixed on 4.1.0
