### ISSUE TITLE
How to get this working on github markdown files?

### ISSUE THREAD

**Issue by sailikk** [nagaozen/markdown-it-toc-done-right#23]
I was searching for this kind of thing so that I could automatically generate a TOC for github markdown files in general, but it does not seem that it is supported right now. The only thing that shows up is ${toc}, no actual table of contents. 

Is there anything that I need to do to enable this on Github or is this not supported?

**Comment by nagaozen** [comment]
Github doesn't use `markdown-it`, so you won't be able to get it working without a browser extension. If you create this plugin, don't hesitate to communicate us and we will help you to promote it.
