### ISSUE TITLE
"Cherry on top" numbering KO when there are lists before the TOC

### ISSUE THREAD

**Issue by fpservant** [nagaozen/markdown-it-toc-done-right#26]
Hi,
it is my experience that the sample code given in the "Cherry on top" paragraph doesn't work correctly if there are lists in the page before the TOC (if you have say 3 lists before the TOC, numbering in the TOC starts at 3). I think this is related to the fact that "list-item" refers to the "[The Implicit list-item Counter](https://www.w3.org/TR/css-lists-3/#list-item-counter)"

I changed the sample code to instantiating its own counter ("list-item-toc"), and got it to work:

```
.table-of-contents ol { counter-reset: list-item-toc; }
.table-of-contents li { display: block; counter-increment: list-item-toc; }
.table-of-contents li:before { content: counters(list-item-toc,'.') ' '; }
```

Thanks for markdown-it-toc-done-right, and happy new year - feliz ano novo

**Comment by nagaozen** [comment]
Thank you
