### ISSUE TITLE
Generate toc in separate div

### ISSUE THREAD

**Issue by userdocs** [nagaozen/markdown-it-toc-done-right#27]
Sorry if i have missed this but I am trying to make the TOC render in a div to the side of the markdown content div and not in the document itself.

I have the TOC showing using a placeholder in my markdown. it just i'd prefer to be able to specify the div that the TOC is shown in instead of being rendered as part of the document.

Is this possible? Like this

https://i.stack.imgur.com/ZDMmW.png

**Comment by nagaozen** [comment]
It's possible to hook on the `callback` option and move the entire TOC into an `<aside>` if you want to.
