### ISSUE TITLE
Is there a way to get JSON format of toc?

### ISSUE THREAD

**Issue by xcatliu** [nagaozen/markdown-it-toc-done-right#30]
I want to get the JSON format of toc and render it in other place. Is there a way to do this?

Just like [markdown-it-title](https://github.com/valeriangalliat/markdown-it-title) does (inject `title` to `env`):

```js
const md = require('markdown-it')({ typographer: true })

md.use(require('markdown-it-title'))

const env = {}
md.render('# Hello, *`world`!(c)*', env)
env.title === 'Hello, world!©'
```

**Comment by nagaozen** [comment]
Yes, there's the `callback : function (html, ast) {}` option.
