### ISSUE TITLE
Tag new version of markdown-it-toc-done-right

### ISSUE THREAD

**Issue by bramceulemans** [nagaozen/markdown-it-toc-done-right#35]
#32 was merged recently. We're using Markdown IT 11 and would like for the warning message to be gone in <https://github.com/blamebutton/docmaker>.

**Comment by DerMolly** [comment]
It would be really nice if you could merge #41 and #42 and then publish a new release. Maybe `4.1.1` or something.

**Comment by nagaozen** [comment]
Done
