### ISSUE TITLE
Option to add toc by default at the beginning of rendered content

### ISSUE THREAD

**Issue by Uzay-G** [nagaozen/markdown-it-toc-done-right#48]
Hi,

I was wondering if it would be possible to add an option to automatically add the table of contents at the beginning of the content. This would be nice instead of manually adding it to the beginning of everything you render.

Thanks!

**Comment by nagaozen** [comment]
I believe that pre-processing the markdown content with a HOC seems to be a better way to achieve this. Something like:

```js
function inject_toc_on_top (md) {
  return ['[TOC]','',md].join('\n')
}

let markdown_content = '# Header'
markdownIt.render(inject_toc_on_top (markdown_content))
```

No reason to address this as an option. Developers have the freedom to decide.
