### ISSUE TITLE
Plugin conflict

### ISSUE THREAD

**Issue by chmorgan** [nagaozen/markdown-it-toc-done-right#5]
Hello.

As I posted in the other issue I’m trying to fix the markdown-it-hierarchy plugin.

I switched approaches to modify the text content to add the hierarchy numbering at the core phrase but unexpectedly I’m seeing a conflict with this plugin.

I had expected the heading id attribute to be used but it looks like because I’m altering the content text this is resulting in the ahref values in the toc using the hierarchy adjusted text, breaking them.

If the id on the heading was “some-section” this is becoming “1.2-some-section” in the toc and is then mismatched with the href on the heading that is/was added to the heading by the anchor plugin.

I’d like my plugin not to conflict with this or any other plugin but I’m not sure what I should be doing differently. Should I not be updating the content during the core phase and do it in another phase? Inserting tags instead? Should this plugin be using the id attribute of the headers instead of recreating it from the text? (I assume this may be due to supporting the anchor plugin running either before or after this plugin, if before then there wouldn’t yet be id attributes)

**Comment by nagaozen** [comment]
It's important to note that numbering headers is not the goal of this plugin and it's the undesired behavior in many scenarios, specially in SEO. That said, what you are probably looking for is a custom `format` function to change the `innerHTML` of the `li`.
