### ISSUE TITLE
Is it possible to place TOC in a different place (from the content)?

### ISSUE THREAD

**Issue by liamb13** [nagaozen/markdown-it-toc-done-right#62]
I'm wondering how I might be able to go about adding the TOC in a different location from the content.
I'm using Vue/Nuxt for my website, and have a repeater for my content (some markdown, some other). 

I'm hoping to be able to achieve the following:
```
<div v-html="$md.render('${toc}\n' + articleCombinedContent)" /> //without articleCombinedContent

<template v-for="(content, index) in article.content">
      <div :key="index" v-if="article.type === 'rich-text'" v-html="$md.render('content.content')" />
      <div :key="index" v-if="article.type === 'spacer'" :class="spacer" />
</template> -->
````

**Comment by nagaozen** [comment]
There is a `markdown-it-toc-done-right` option `callback` which is fired with html and ast as arguments. You can use it to store either of the values to use in another place.

**Comment by matthewmorek** [comment]
@nagaozen Any suggestions or example of how `callback` could be used to store or inject either of the values to a given route's state?

I'm trying to make this work with `vite-plugin-pages` and `vite-plugin-vue-layouts`, but after spending hours searching through code utilising this package, as well as through Vite's docs and additional configuration options for `vite-plugin-md` I came up empty.

Even a handy pointer would do, as I'm not sure where else to look. Thanks!
