### ISSUE TITLE
I'd like to give an [.active] class to the chosen item. 

### ISSUE THREAD

**Issue by jjulee** [nagaozen/markdown-it-toc-done-right#63]
environment : vuecli 3 + typescript

I'd like to add a class to give a different style just the item I clicked on.
What should I do?

Help me~

**Comment by nagaozen** [comment]
This feature is out-of-scope of this project. If you are running in the server, you could observer the URL hash property to highlight it in the server before dispatching the results to the client (by patching the response). If you are working on client, just manage the current item state in javascript.
